Repository TweetWallFX/TweetwallFX-Devoxx-2018-BE, pull requests merged in 2018-11, with the labels that each got.

#24 Added convenience tasks running the wall projects
  build.gradle
Labels: enhancement

#34 Upgraded tweetwall libs dto version 1.0.+
  gradle.properties
Labels: dependency

#33 added end time to upcoming schedule slot.
  stepengine/src/main/java/org/tweetwallfx/devoxx18be/steps/Devoxx18ShowSchedule.java
  stepengine/src/main/java/org/tweetwallfx/devoxx18be/steps/exhibition/Devoxx18ShowSchedule.java
Labels: enhancement

#56 Fix positions and length of tweet stream display. See #19
  cinema2k/src/main/resources/tweetwallConfig.json
Labels: bug
